apiVersion: apps/v1
kind: Deployment
metadata:
  name: normas-api
  namespace: sigo-ms
  labels:
    name: normas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: normas-api
  template:
    metadata:
      labels:
        name: normas-api
    spec:
      containers:
        - name: sigo-ms-gestao-normas
          imagePullPolicy: Always
          image: juniormichieletto/sigo-ms-gestao-normas:latest
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: normas-api
  namespace: sigo-ms
spec:
  type: ClusterIP
  selector:
      name: normas-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: normas-api
  namespace: sigo-ms
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: normas-api
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90