apiVersion: apps/v1
kind: Deployment
metadata:
  name: normas-api
  namespace: sigo-ms
  labels:
    name: normas-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: normas-api
  template:
    metadata:
      labels:
        name: normas-api
    spec:
      containers:
        - name: sigo-ms-gestao-normas
          imagePullPolicy: Always
          image: juniormichieletto/sigo-ms-gestao-normas:latest
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: normas-api
  namespace: sigo-ms
spec:
  selector:
    app: normas-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080