apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app-type: sigo-ms-gestaonormas
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: sigo-ms-gestao-normas
  name: sigo-ms-gestao-normas
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: sigo-ms-gestao-normas
  template:
    metadata:
      labels:
        app-type: sigo-ms-gestaonormas
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: sigo-ms-gestao-normas
    spec:
      containers:
      - name: sigo-ms-gestao-normas
        imagePullPolicy: Always
        image: juniormichieletto/sigo-ms-gestao-normas:latest
        envFrom:
          - secretRef:
              name: postgres-secret
          - configMapRef:
              name: postgres-config
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: sigo-ms-gestao-normas
    app-type: sigo-ms-gestaonormas
  name: sigo-ms-gestao-normas
spec:
  selector:
    app.kubernetes.io/name: sigo-ms-gestao-normas
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000