# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build package with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker image with Maven
      run: mvn clean package -DskipTests -Dquarkus.container-image.build=true -Dquarkus.container-image.group=juniormichieletto
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: juniormichieletto/sigo-ms-gestao-normas
        tag_with_ref: true