# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build package with Maven
      run: mvn -B package --file pom.xml
    - name: Build docker image
      run: mvn clean package -DskipTests -Dquarkus.container-image.build=true -Dquarkus.container-image.group=juniormichieletto -Dquarkus.container-image.tag=latest
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub
      run: docker push juniormichieletto/sigo-ms-gestao-normas
